# Generated by Django 5.0.3 on 2024-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_music_artist_alter_music_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='music_track',
        ),
        migrations.AddField(
            model_name='folder',
            name='music_track',
            field=models.ManyToManyField(to='app.music'),
        ),
    ]
