# Generated by Django 5.0.3 on 2024-03-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_folder_music_track_folder_music_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='fav', max_length=20),
        ),
    ]
